### ISSUE TITLE
Please share some howto information

### ISSUE THREAD

**Issue by cmonty14** [sobrus/FastLacellsGenerator#2]
Hello!

Could you please provide some additional information for the usage of this script?
E.g. where should I run this script? On PC or phone device?
Where will the database file be stored?
Where can I identify the MCC matching to my country / localization?

THX

**Comment by sobrus** [comment]
Hi :) 

This script is intended to run on PC. Moreover, since it is a bash script, ideally it should be executed on some kind of Unix-like machine (or Linux). It uses some unix programs like gunzip, sqlite3 and grep. I believe it should run on windows with Cygwin.

You don't need it on your phone, since GSM backend (by n76) already supports creating databases on phone with a nice GUI :) and with automatic OpenCellID API key generation - and this is the simplest method to generate cell database (this script can only do it faster)

Using this script, database will be written to current working directory (usually the one containing script itself).

As for MCC, there is nice page on wikipedia with all codes listed and explained :)
https://en.wikipedia.org/wiki/Mobile_country_code

**Comment by xuhdev** [comment]
@sobrus Can you also put some info on where to put the generated database :) I couldn't find any instructions.

**Comment by sobrus** [comment]
Since version 1.4.4 of Local-GSM-Backend you can put the database anywhere you want (just set this path in backend settings).
By default (and in older versions of backend), it should be located on first sdcard (most probably phone internal memory) in directory

Android/data/org.fitchfamily.android.gsmlocation/files
