### ISSUE TITLE
Config RCO_SRC_FILE for 2 countries

### ISSUE THREAD

**Issue by cmonty14** [sobrus/FastLacellsGenerator#7]
Hi,
you recommend to set RCO_SRC_FILE="openbmap.sqlite" for the world and RCO_SRC_FILE="--countrycode--.sqlite" for a single country.
But what is the parameter for 2 countries?

THX

**Comment by sobrus** [comment]
Hi, and sorry that you had to wait so long for my reply.

Unfortunately, since radiocells website doesn't provide downloads for sets of countries, so for multiple countries you need to download whole world database.

Even though, all data will be filtered to countries set in MCC parameter (just like in other sources) - it will only take longer to download and process whole world database.
